//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaPelicula
    {
        public VentaPelicula()
        {
            this.VentaDetallePelicula = new HashSet<VentaDetallePelicula>();
            this.DevolucionesPeliculas = new HashSet<DevolucionesPeliculas>();
        }
    
        public long IdVenta { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string EstatusVenta { get; set; }
        public bool EstadoVenta { get; set; }
        public long IdUsuario { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<decimal> ISV { get; set; }
        public Nullable<decimal> TotalVenta { get; set; }
    
        public virtual ICollection<VentaDetallePelicula> VentaDetallePelicula { get; set; }
        public virtual ICollection<DevolucionesPeliculas> DevolucionesPeliculas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
