//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clasificaciones
    {
        public Clasificaciones()
        {
            this.Peliculas = new HashSet<Peliculas>();
        }
    
        public byte IdClasificaciones { get; set; }
        public string DescripcionClasficacion { get; set; }
        public bool EstadoClasificacion { get; set; }
    
        public virtual ICollection<Peliculas> Peliculas { get; set; }
    }
}
