//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public Peliculas()
        {
            this.VentaDetallePelicula = new HashSet<VentaDetallePelicula>();
            this.DevolucionDetalle = new HashSet<DevolucionDetalle>();
        }
    
        public long IdPelicula { get; set; }
        public string NombrePelicula { get; set; }
        public string NombreCorto { get; set; }
        public System.DateTime FechaLanzamiento { get; set; }
        public byte FKIdTipoPelicula { get; set; }
        public byte FKIdClasificacion { get; set; }
        public int FKIdEstudio { get; set; }
        public bool Estreno { get; set; }
        public decimal PrecioVenta { get; set; }
        public bool EstadoPelicula { get; set; }
        public string Exento { get; set; }
        public string DireccionImagen { get; set; }
        public byte[] ImagenPel { get; set; }
    
        public virtual Clasificaciones Clasificaciones { get; set; }
        public virtual Estudios Estudios { get; set; }
        public virtual TiposPeliculas TiposPeliculas { get; set; }
        public virtual ICollection<VentaDetallePelicula> VentaDetallePelicula { get; set; }
        public virtual ICollection<DevolucionDetalle> DevolucionDetalle { get; set; }
    }
}
