//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilModulo
    {
        public short FKPerfilId { get; set; }
        public short FKModuloId { get; set; }
        public long IdPerfilModulo { get; set; }
    
        public virtual Perfiles Perfiles { get; set; }
        public virtual Modulos Modulos { get; set; }
    }
}
