//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryStreaingUnicah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.VentaPelicula = new HashSet<VentaPelicula>();
        }
    
        public long IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string NombreCompleto { get; set; }
        public System.DateTime FechaNacimeinto { get; set; }
        public string CorreoElectronico { get; set; }
        public short FKPerfil { get; set; }
        public bool Estdo { get; set; }
        public string Contrasenia { get; set; }
    
        public virtual Perfiles Perfiles { get; set; }
        public virtual ICollection<VentaPelicula> VentaPelicula { get; set; }
    }
}
